Repository Kazuki0320/GolfApp, pull requests merged in 2023-01, with the labels that each got.

#31 Feature/survey creation screen
  package-lock.json
  package.json
  src/Vuex/store.js
  src/components/layouts/DefaultSidebar.vue
  src/main.js
  src/plugins/vuetify.js
  src/router/index.js
  src/views/NewSurvey.vue
  src/views/SurveyAnswer.vue
  src/views/SurveyConfirmed.vue
  src/views/UsersList.vue
  src/views/UsersSearch.vue
Labels: 優先度高

#38 🩹 eslintrcのrules追加: 本当は良くないと思われるが、実行できなかったので暫定対応
  .eslintrc.js
Labels: 検討事項有

#40 🐛 [newServey]フレンドがいない場合の例外処理を追加
  src/views/NewSurvey.vue
Labels: 優先度低い

#43 [surveyConfirmed]アンケート作成して「メッセージ送信」したタイミングで、roomsのmessageにquestionnairesIdを追加する処理
  src/router/index.js
  src/views/ChatBoard.vue
  src/views/NewSurvey.vue
  src/views/SurveyConfirmed.vue
  src/views/roomList.vue
Labels: 優先度高

#47 【Feature/survey creation answer】アンケート回答者の画面実装
  src/views/ChatBoard.vue
  src/views/SurveyAnswer.vue
  src/views/SurveyConfirmed.vue
  src/views/roomList.vue
Labels: 優先度高

#63 ✨ アンケート作成画面のバリデーションを追加
  src/views/NewSurvey.vue
Labels: 優先度高

#64 【surveyResults/surveyResultsAnswer】✨アンケート集計画面の実装及び微修正
  src/components/layouts/DefaultSidebar.vue
  src/router/index.js
  src/views/SurveyConfirmed.vue
  src/views/SurveyResults.vue
  src/views/SurveyResultsAnswer.vue
Labels: 優先度高
